version: '3'

services:
  mysql:
    image: mysql:5.7.24
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./.data/mysql:/var/lib/mysql
#      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#      - ./mysql/docker-entrypoint-initdb.d:/sailx_start.d
  app:
    build:
      context: ./app
    ports:
      - 80:80
    volumes:
      - ./app/src/ttm:/var/www/app/
    depends_on:
      - mysql
      - redis
    environment:
      - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}

  composer:
    image: composer:1.6
    volumes:
      - ./app/src/ttm:/var/www/app/
    working_dir: /var/www/app/
    command: composer install

  redis:
        image: redis:4.0
        ports:
          - "6379:6379"
