version: "3.3"

services:
  mysql:
    image: mysql:5.7.24
    ports:
      - "3306:3306"
      - "9004:9004"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./.data/mysql:/var/lib/mysql

  app:
    build:
      context: ./app
    ports:
      - "80:80"
    environment:
      PHP_IDE_CONFIG: "serverName=tortuga.dep"
      PHP_EXTENSION_XDEBUG: 1
    volumes:
      - ./app/src/tortuga/:/var/www/app/tortuga:cached
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"

  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./.data/clickhouse:/var/lib/clickhouse
      - ./clickhouse/configs/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/configs/dictionary:/etc/clickhouse-server/dictionary/
#      - ./clickhouse/configs/accom_dictionary.xml:/etc/clickhouse-server/accom_dictionary.xml
#      - ./clickhouse/configs/dic_statuses_dictionary.xml:/etc/clickhouse-server/dic_statuses_dictionary.xml
#      - ./clickhouse/configs/tb_gosb_dictionary.xml:/etc/clickhouse-server/tb_gosb_dictionary.xml
#      - ./clickhouse/configs/users_dictionary.xml:/etc/clickhouse-server/users_dictionary.xml
