version: '3'

services:
  mysql:
    image: mysql:5.7.24
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./.data/mysql:/var/lib/mysql

  app:
    build:
      context: ./app
    ports:
      - 80:80
    volumes:
      - ./app/src:/var/www/app/
    depends_on:
      - mysql
      - redis
      - composer

  composer:
    image: composer:1.6
    volumes:
      - ./app/src:/var/www/app/
    working_dir: /var/www/app/
    command: composer install

  redis:
        image: redis:4.0
        ports:
          - "6379:6379"
