version: "3.3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.24
    ports:
      - "3306:3306"
      - "9004:9004"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

  app-unison:
    container_name: app
    build:
      context: ./app
    ports:
      - "80:80"
    environment:
      PHP_EXTENSION_XDEBUG: 1
    depends_on:
      - mysql
      - redis
      - clickhouse

  redis:
    container_name: redis
    image: redis:4.0
    ports:
      - "6379:6379"

  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./.data/clickhouse:/var/lib/clickhouse
      # General config
      - ./clickhouse/configs/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/configs/users.xml:/etc/clickhouse-server/users.xml
      # Dictionary
      - ./clickhouse/configs/dictionary:/etc/clickhouse-server/dictionary/
      # Dump your Clickhouse
      - ./clickhouse/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d

