version: '3'

services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD 
    volumes:
      - ./.data/mysql:/var/lib/mysql
#      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    build:
      context: ./app
    ports:
      - 80:80
    volumes:
      - ./app/src/:/var/www/app/
    depends_on:
      - mysql

  composer:
    image: composer:1.6
    volumes:
      - ./app/src/:/var/www/app/
    working_dir: /var/www/app/
    command: composer install
